---

- hosts: all
  become: true
  tasks:

  - name: update apt index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache package
    apt: 
      name: apache2
    when: ansible_distribution == "Ubuntu"

  - name: update yum index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd package
    yum:
      name: httpd
    when: ansible_distribution == "CentOS"


